server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:dbaas-db-9161788-do-user-16562805-0.c.db.ondigitalocean.com}:${DB_PORT:25060}/defaultdb
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/etlas_db
    username: doadmin
    password: ${DB_PASSWORD:AVNS_iOmaPoiL-Ako1xBMbug}
#    password: AVNS_33I90Bz-upYSct1tA1p
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  flyway:
    baseline-on-migrate: true
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: cydeo.ticketing@gmail.com
    password: uaiw wvms yzqu ybdy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#host-service-port: http://ec2-3-126-153-218.eu-central-1.compute.amazonaws.com:8080

#  host-service-port: http://localhost:8080