server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://etlas-db.c7u4u22ysmqt.eu-central-1.rds.amazonaws.com/etlas_db
#    url: jdbc:postgresql://localhost:5432/etlas_db
    username: etlas
    password: Etlas#281
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  flyway:
    baseline-on-migrate: true
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: cydeo.ticketing@gmail.com
    password: uaiw wvms yzqu ybdy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#host-service-port: http://ec2-3-126-153-218.eu-central-1.compute.amazonaws.com:8080

#  host-service-port: http://localhost:8080