
insert into users(insert_date_time, insert_user_id, is_deleted, last_update_date_time, last_update_user_id, enabled,
                  first_name, gender, last_name, user_name, role, pass_word)
values ('2024-02-22 00:00:00', 1, false, '2024-02-22 00:00:00', 1, true, 'admin', 'MALE', 'admin', 'admin@etlas.com','ADMIN','$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-02-23 00:00:00', 2, false, '2024-02-23 00:00:00', 1, true, 'Yusuf', 'MALE', 'Muhammed', 'yusuf@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-02-24 00:00:00', 3, false, '2024-02-24 00:00:00', 1, true, 'Jane', 'FEMALE', 'Smith', 'jane.smith@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-02-25 00:00:00', 4, false, '2024-02-25 00:00:00', 1, true, 'Michael', 'MALE', 'Johnson', 'michael.johnson@etlas.com', 'EMPLOYEE', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-02-26 00:00:00', 5, false, '2024-02-26 00:00:00', 1, true, 'Emily', 'FEMALE', 'Williams', 'emily.williams@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-02-27 00:00:00', 6, false, '2024-02-27 00:00:00', 1, true, 'David', 'MALE', 'Brown', 'david.brown@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-02-28 00:00:00', 7, false, '2024-02-28 00:00:00', 1, true, 'Abdusamet', 'MALE', 'Uyghur', 'abdusamet@etlas.com', 'EMPLOYEE', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-02-29 00:00:00', 8, false, '2024-02-29 00:00:00', 1, true, 'Daniel', 'MALE', 'Davis', 'daniel.davis@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-01 00:00:00', 9, false, '2024-03-01 00:00:00', 1, true, 'Sophia', 'FEMALE', 'Taylor', 'sophia.taylor@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-02 00:00:00', 10, false, '2024-03-02 00:00:00', 1, true, 'Christopher', 'MALE', 'Moore', 'christopher.moore@etlas.com', 'EMPLOYEE', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-03 00:00:00', 11, false, '2024-03-03 00:00:00', 1, true, 'Abduhabir', 'MALE', 'akyol', 'akyol@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-04 00:00:00', 12, false, '2024-03-04 00:00:00', 1, true, 'Ethan', 'MALE', 'Anderson', 'ethan.anderson@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-05 00:00:00', 13, false, '2024-03-05 00:00:00', 1, true, 'Isabella', 'FEMALE', 'Martinez', 'isabella.martinez@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-06 00:00:00', 14, false, '2024-03-06 00:00:00', 1, true, 'Jackson', 'MALE', 'Lee', 'jackson.lee@etlas.com', 'EMPLOYEE', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-07 00:00:00', 15, false, '2024-03-07 00:00:00', 1, true, 'Sophie', 'FEMALE', 'Perez', 'sophie.perez@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-08 00:00:00', 16, false, '2024-03-08 00:00:00', 1, true, 'Caleb', 'MALE', 'Wilson', 'caleb.wilson@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-09 00:00:00', 17, false, '2024-03-09 00:00:00', 1, true, 'Avery', 'FEMALE', 'Taylor', 'avery.taylor@etlas.com', 'EMPLOYEE', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-10 00:00:00', 18, false, '2024-03-10 00:00:00', 1, true, 'Henry', 'MALE', 'Brown', 'henry.brown@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-11 00:00:00', 19, false, '2024-03-11 00:00:00', 1, true, 'Lily', 'FEMALE', 'Garcia', 'lily.garcia@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-12 00:00:00', 20, false, '2024-03-12 00:00:00', 1, true, 'Samuel', 'MALE', 'Miller', 'samuel.miller@etlas.com', 'EMPLOYEE', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-13 00:00:00', 21, false, '2024-03-13 00:00:00', 1, true, 'Scarlett', 'FEMALE', 'Anderson', 'scarlett.anderson@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-14 00:00:00', 22, false, '2024-03-14 00:00:00', 1, true, 'Gabriel', 'MALE', 'Moore', 'gabriel.moore@etlas.com', 'MANAGER', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-15 00:00:00', 23, false, '2024-03-15 00:00:00', 1, true, 'Hazel', 'FEMALE', 'Robinson', 'hazel.robinson@etlas.com', 'EMPLOYEE', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK'),
       ('2024-03-16 00:00:00', 24, false, '2024-03-16 00:00:00', 1, true, 'Owen', 'MALE', 'Young', 'owen.young@etlas.com', 'ADMIN', '$2a$10$nAB5j9G1c3JHgg7qzhiIXO7cqqr5oJ3LXRNQJKssDUwHXzDGUztNK');

-- Abc1


insert into customers(insert_date_time, insert_user_id, is_deleted, last_update_date_time, last_update_user_id,
                      customer_type,first_name, last_name, gender,email, phone_number,country,company_name,office_number, customertrybalance, customerusdbalance,customereurbalance)
values
    -- companies
    ('2024-02-22 00:00:00', 1, false, '2024-02-22 00:00:00', 1, 'COMPANY',null,null,null,'pebeda@mailinator.com','05352843345','USA','Ramsey Duran LLC','02124443333',6500,150,360),
    ('2024-02-23 00:00:00', 2, false, '2024-02-23 00:00:00', 1, 'COMPANY', null, null, null, 'johncompany@mailinator.com', '05461234567', 'CAN', 'Smith Enterprises', '', 8000, 200, 400),
    ('2024-02-24 00:00:00', 3, false, '2024-02-24 00:00:00', 1, 'COMPANY', null, null, null, 'janecompany@mailinator.com', '05327894561', 'GBR', 'Johnson & Co.', '02211223344', 9500, 300, 500),
    ('2024-02-25 00:00:00', 4, false, '2024-02-25 00:00:00', 1, 'COMPANY', null, null, null, 'mikecompany@mailinator.com', '05578901234', 'DEU', 'Miller Corp', '03099887766', 7000, 100, 300),
    ('2024-02-26 00:00:00', 5, false, '2024-02-26 00:00:00', 1, 'COMPANY', null, null, null, 'emilycompany@mailinator.com', '05234567890', 'FRA', 'White Industries', '04233445566', 8500, 250, 450),
    ('2024-02-27 00:00:00', 6, false, '2024-02-27 00:00:00', 1, 'COMPANY', null, null, null, 'davidcompany@mailinator.com', '05678901234', 'USA', 'Brown & Sons', '01122334455', 6000, 50, 250),
    ('2024-02-28 00:00:00', 7, false, '2024-02-28 00:00:00', 1, 'COMPANY', null, null, null, 'oliviacompany@mailinator.com', '05123456789', 'CAN', 'Jones Ltd.', '', 7500, 150, 350),
    ('2024-02-29 00:00:00', 8, false, '2024-02-29 00:00:00', 1, 'COMPANY', null, null, null, 'danielcompany@mailinator.com', '05890123456', 'GBR', 'Davis Enterprises', '03322110044', 9000, 200, 400),
    ('2024-03-01 00:00:00', 9, false, '2024-03-01 00:00:00', 1, 'COMPANY', null, null, null, 'sophiacompany@mailinator.com', '05012345678', 'DEU', 'Taylor Holdings', '04455667788', 6500, 100, 300),
    ('2024-03-02 00:00:00', 10, false, '2024-03-02 00:00:00', 1, 'COMPANY', null, null, null, 'christophercompany@mailinator.com', '05456789012', 'FRA', 'Moore & Co.', '05566778899', 8000, 150, 350),
    ('2024-03-03 00:00:00', 11, false, '2024-03-03 00:00:00', 1, 'COMPANY', null, null, null, 'avacompany@mailinator.com', '05901234567', 'USA', 'White Corporation', '01122334455', 7500, 100, 300),
    ('2024-03-04 00:00:00', 12, false, '2024-03-04 00:00:00', 1, 'COMPANY', null, null, null, 'ethancompany@mailinator.com', '05234567890', 'CAN', 'Anderson Holdings', '', 9000, 200, 400),
    ('2024-03-05 00:00:00', 13, false, '2024-03-05 00:00:00', 1, 'COMPANY', null, null, null, 'isabellacompany@mailinator.com', '05789012345', 'GBR', 'Martinez Ltd.', '02211223344', 6500, 50, 250),
    ('2024-03-06 00:00:00', 14, false, '2024-03-06 00:00:00', 1, 'COMPANY', null, null, null, 'jacksoncompany@mailinator.com', '05323456789', 'DEU', 'Lee & Sons', '03112233445', 8000, 150, 350),
    ('2024-03-07 00:00:00', 15, false, '2024-03-07 00:00:00', 1, 'COMPANY', null, null, null, 'sophiecompany@mailinator.com', '05901234567', 'FRA', 'Perez Corporation', '04223334455', 7000, 100, 300),
    ('2024-03-08 00:00:00', 16, false, '2024-03-08 00:00:00', 1, 'COMPANY', null, null, null, 'calebcompany@mailinator.com', '05789012345', 'USA', 'Wilson Holdings', '01234567890', 8500, 200, 400),
    ('2024-03-09 00:00:00', 17, false, '2024-03-09 00:00:00', 1, 'COMPANY', null, null, null, 'averycompany@mailinator.com', '05123456789', 'CAN', 'Taylor Enterprises', '', 7000, 50, 250),

    -- Individuals
    ('2024-03-10 00:00:00', 18, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Osman', 'Uygur', 'MALE', 'henrycompany@mailinator.com', '05678901234', 'GBR', null, null, 5400, 450, 185),
    ('2024-03-11 00:00:00', 19, false, '2024-03-11 00:00:00', 1, 'INDIVIDUAL', 'Sophia', 'Johnson', 'FEMALE', 'sophia@mailinator.com', '05123456789', 'USA', null, null, 7200, 550, 210),
    ('2024-03-12 00:00:00', 20, false, '2024-03-12 00:00:00', 1, 'INDIVIDUAL', 'Ethan', 'Smith', 'MALE', 'ethan@mailinator.com', '05456789012', 'CAN', null, null, 6100, 500, 195),
    ('2024-03-13 00:00:00', 21, false, '2024-03-13 00:00:00', 1, 'INDIVIDUAL', 'Ava', 'Brown', 'FEMALE', 'ava@mailinator.com', '05901234567', 'TUR', null, null, 8000, 700, 280),
    ('2024-03-14 00:00:00', 22, false, '2024-03-14 00:00:00', 1, 'INDIVIDUAL', 'Liam', 'Martinez', 'MALE', 'liam@mailinator.com', '05567890123', 'FRA', null, null, 4700, 400, 165),
    ('2024-03-15 00:00:00', 23, false, '2024-03-15 00:00:00', 1, 'INDIVIDUAL', 'Emma', 'Lee', 'FEMALE', 'emma@mailinator.com', '05234567890', 'USA', null, null, 6900, 600, 245),
    ('2024-03-16 00:00:00', 24, false, '2024-03-16 00:00:00', 1, 'INDIVIDUAL', 'Noah', 'White', 'MALE', 'noah@mailinator.com', '05678901234', 'CAN', null, null, 5800, 550, 230),
    ('2024-03-17 00:00:00', 25, false, '2024-03-17 00:00:00', 1, 'INDIVIDUAL', 'Olivia', 'Davis', 'FEMALE', 'olivia@mailinator.com', '05345678901', 'GBR', null, null, 7700, 650, 265),
    ('2024-03-18 00:00:00', 26, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Liam', 'Taylor', 'MALE', 'liamtaylor@mailinator.com', '05789012345', 'TUR', null, null, 6300, 500, 205),
    ('2024-03-19 00:00:00', 27, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Ava', 'Moore', 'FEMALE', 'avamoore@mailinator.com', '05456789012', 'FRA', null, null, 7100, 600, 240),
    ('2024-03-20 00:00:00', 28, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Oliver', 'Robinson', 'MALE', 'oliverrobinson@mailinator.com', '05901234567', 'USA', null, null, 5500, 450, 185),
    ('2024-03-21 00:00:00', 29, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Emma', 'Young', 'FEMALE', 'emmayoung@mailinator.com', '05345678901', 'CAN', null, null, 7400, 700, 275),
    ('2024-03-22 00:00:00', 30, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Mia', 'Anderson', 'FEMALE', 'mia@mailinator.com', '05789012345', 'GBR', null, null, 6000, 550, 220),
    ('2024-03-23 00:00:00', 31, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Lucas', 'Garcia', 'MALE', 'lucasgarcia@mailinator.com', '05456789012', 'TUR', null, null, 7900, 750, 300),
    ('2024-03-24 00:00:00', 32, false, '2024-03-10 00:00:00', 1, 'INDIVIDUAL', 'Sophia', 'Taylor', 'FEMALE', 'sophiataylor@mailinator.com', '05901234567', 'FRA', null, null, 6500, 600, 245);


-- INSERT INTO CountriesEN (iso2, iso3, name) VALUES
--                                            ('AF', 'AFG', 'Afghanistan'),
--                                            ('AX', 'ALA', 'Aland Islands'),
--                                            ('AL', 'ALB', 'Albania'),
--                                            ('DZ', 'DZA', 'Algeria'),
--                                            ('AS', 'ASM', 'American Samoa'),
--                                            ('AD', 'AND', 'Andorra'),
--                                            ('AO', 'AGO', 'Angola'),
--                                            ('AI', 'AIA', 'Anguilla'),
--                                            ('AQ', 'ATA', 'Antarctica'),
--                                            ('AG', 'ATG', 'Antigua And Barbuda'),
--                                            ('AR', 'ARG', 'Argentina'),
--                                            ('AM', 'ARM', 'Armenia'),
--                                            ('AW', 'ABW', 'Aruba'),
--                                            ('AU', 'AUS', 'Australia'),
--                                            ('AT', 'AUT', 'Austria'),
--                                            ('AZ', 'AZE', 'Azerbaijan'),
--                                            ('BS', 'BHS', 'The Bahamas'),
--                                            ('BH', 'BHR', 'Bahrain'),
--                                            ('BD', 'BGD', 'Bangladesh'),
--                                            ('BB', 'BRB', 'Barbados'),
--                                            ('BY', 'BLR', 'Belarus'),
--                                            ('BE', 'BEL', 'Belgium'),
--                                            ('BZ', 'BLZ', 'Belize'),
--                                            ('BJ', 'BEN', 'Benin'),
--                                            ('BM', 'BMU', 'Bermuda'),
--                                            ('BT', 'BTN', 'Bhutan'),
--                                            ('BO', 'BOL', 'Bolivia'),
--                                            ('BA', 'BIH', 'Bosnia and Herzegovina'),
--                                            ('BW', 'BWA', 'Botswana'),
--                                            ('BV', 'BVT', 'Bouvet Island'),
--                                            ('BR', 'BRA', 'Brazil'),
--                                            ('IO', 'IOT', 'British Indian Ocean Territory'),
--                                            ('BN', 'BRN', 'Brunei'),
--                                            ('BG', 'BGR', 'Bulgaria'),
--                                            ('BF', 'BFA', 'Burkina Faso'),
--                                            ('BI', 'BDI', 'Burundi'),
--                                            ('KH', 'KHM', 'Cambodia'),
--                                            ('CM', 'CMR', 'Cameroon'),
--                                            ('CA', 'CAN', 'Canada'),
--                                            ('CV', 'CPV', 'Cape Verde'),
--                                            ('KY', 'CYM', 'Cayman Islands'),
--                                            ('CF', 'CAF', 'Central African Republic'),
--                                            ('TD', 'TCD', 'Chad'),
--                                            ('CL', 'CHL', 'Chile'),
--                                            ('CN', 'CHN', 'China'),
--                                            ('CX', 'CXR', 'Christmas Island'),
--                                            ('CC', 'CCK', 'Cocos (Keeling) Islands'),
--                                            ('CO', 'COL', 'Colombia'),
--                                            ('KM', 'COM', 'Comoros'),
--                                            ('CG', 'COG', 'Congo'),
--                                            ('CD', 'COD', 'Democratic Republic of the Congo'),
--                                            ('CK', 'COK', 'Cook Islands'),
--                                            ('CR', 'CRI', 'Costa Rica'),
--                                            ('CI', 'CIV', 'Cote D''Ivoire (Ivory Coast)'),
--                                            ('HR', 'HRV', 'Croatia'),
--                                            ('CU', 'CUB', 'Cuba'),
--                                             ('CY', 'CYP', 'Cyprus'),
--                                             ('CZ', 'CZE', 'Czech Republic'),
--                                             ('DK', 'DNK', 'Denmark'),
--                                             ('DJ', 'DJI', 'Djibouti'),
--                                             ('DM', 'DMA', 'Dominica'),
--                                             ('DO', 'DOM', 'Dominican Republic'),
--                                             ('ET', 'EST', 'East Turkistan'),
--                                             ('TL', 'TLS', 'East Timor'),
--                                             ('EC', 'ECU', 'Ecuador'),
--                                             ('EG', 'EGY', 'Egypt'),
--                                             ('SV', 'SLV', 'El Salvador'),
--                                             ('GQ', 'GNQ', 'Equatorial Guinea'),
--                                             ('ER', 'ERI', 'Eritrea'),
--                                             ('EE', 'EST', 'Estonia'),
--                                             ('ET', 'ETH', 'Ethiopia'),
--                                             ('FK', 'FLK', 'Falkland Islands'),
--                                             ('FO', 'FRO', 'Faroe Islands'),
--                                             ('FJ', 'FJI', 'Fiji Islands'),
--                                             ('FI', 'FIN', 'Finland'),
--                                             ('FR', 'FRA', 'France'),
--                                             ('GF', 'GUF', 'French Guiana'),
--                                             ('PF', 'PYF', 'French Polynesia'),
--                                             ('TF', 'ATF', 'French Southern Territories'),
--                                             ('GA', 'GAB', 'Gabon'),
--                                             ('GM', 'GMB', 'Gambia The'),
--                                             ('GE', 'GEO', 'Georgia'),
--                                             ('DE', 'DEU', 'Germany'),
--                                             ('GH', 'GHA', 'Ghana'),
--                                             ('GI', 'GIB', 'Gibraltar'),
--                                             ('GR', 'GRC', 'Greece'),
--                                             ('GL', 'GRL', 'Greenland'),
--                                             ('GD', 'GRD', 'Grenada'),
--                                             ('GP', 'GLP', 'Guadeloupe'),
--                                             ('GU', 'GUM', 'Guam'),
--                                             ('GT', 'GTM', 'Guatemala'),
--                                             ('GG', 'GGY', 'Guernsey and Alderney'),
--                                             ('GN', 'GIN', 'Guinea'),
--                                             ('GW', 'GNB', 'Guinea-Bissau'),
--                                             ('GY', 'GUY', 'Guyana'),
--                                             ('HT', 'HTI', 'Haiti'),
--                                             ('HM', 'HMD', 'Heard Island and McDonald Islands'),
--                                             ('HN', 'HND', 'Honduras'),
--                                             ('HK', 'HKG', 'Hong Kong SAR'),
--                                             ('HU', 'HUN', 'Hungary'),
--                                             ('IS', 'ISL', 'Iceland'),
--                                             ('IN', 'IND', 'India'),
--                                             ('ID', 'IDN', 'Indonesia'),
--                                             ('IR', 'IRN', 'Iran'),
--                                             ('IQ', 'IRQ', 'Iraq'),
--                                             ('IE', 'IRL', 'Ireland'),
--                                             ('IM', 'IMN', 'Isle of Man'),
--                                             ('IL', 'ISR', 'Israel'),
--                                             ('IT', 'ITA', 'Italy'),
--                                             ('JM', 'JAM', 'Jamaica'),
--                                             ('JP', 'JPN', 'Japan'),
--                                             ('JE', 'JEY', 'Jersey'),
--                                             ('JO', 'JOR', 'Jordan'),
--                                             ('KZ', 'KAZ', 'Kazakhstan'),
--                                             ('KE', 'KEN', 'Kenya'),
--                                             ('KI', 'KIR', 'Kiribati'),
--                                             ('KP', 'PRK', 'Korea North'),
--                                             ('KR', 'KOR', 'Korea South'),
--                                             ('KW', 'KWT', 'Kuwait'),
--                                             ('KG', 'KGZ', 'Kyrgyzstan'),
--                                             ('LA', 'LAO', 'Laos'),
--                                             ('LV', 'LVA', 'Latvia'),
--                                             ('LB', 'LBN', 'Lebanon'),
--                                             ('LS', 'LSO', 'Lesotho'),
--                                             ('LR', 'LBR', 'Liberia'),
--                                             ('LY', 'LBY', 'Libya'),
--                                             ('LI', 'LIE', 'Liechtenstein'),
--                                             ('LT', 'LTU', 'Lithuania'),
--                                             ('LU', 'LUX', 'Luxembourg'),
--                                             ('MO', 'MAC', 'Macao SAR'),
--                                             ('MK', 'MKD', 'North Macedonia'),
--                                             ('MG', 'MDG', 'Madagascar'),
--                                             ('MW', 'MWI', 'Malawi'),
--                                             ('MY', 'MYS', 'Malaysia'),
--                                             ('MV', 'MDV', 'Maldives'),
--                                             ('ML', 'MLI', 'Mali'),
--                                             ('MT', 'MLT', 'Malta'),
--                                             ('MH', 'MHL', 'Marshall Islands'),
--                                             ('MQ', 'MTQ', 'Martinique'),
--                                             ('MR', 'MRT', 'Mauritania'),
--                                             ('MU', 'MUS', 'Mauritius'),
--                                             ('YT', 'MYT', 'Mayotte'),
--                                             ('MX', 'MEX', 'Mexico'),
--                                             ('FM', 'FSM', 'Micronesia'),
--                                             ('MD', 'MDA', 'Moldova'),
--                                             ('MC', 'MCO', 'Monaco'),
--                                             ('MN', 'MNG', 'Mongolia'),
--                                             ('ME', 'MNE', 'Montenegro'),
--                                             ('MS', 'MSR', 'Montserrat'),
--                                             ('MA', 'MAR', 'Morocco'),
--                                             ('MZ', 'MOZ', 'Mozambique'),
--                                             ('MM', 'MMR', 'Myanmar'),
--                                             ('NA', 'NAM', 'Namibia'),
--                                             ('NR', 'NRU', 'Nauru'),
--                                             ('NP', 'NPL', 'Nepal'),
--                                             ('NL', 'NLD', 'Netherlands'),
--                                             ('AN', 'ANT', 'Netherlands Antilles'),
--                                             ('NC', 'NCL', 'New Caledonia'),
--                                             ('NZ', 'NZL', 'New Zealand'),
--                                             ('NI', 'NIC', 'Nicaragua'),
--                                             ('NE', 'NER', 'Niger'),
--                                             ('NG', 'NGA', 'Nigeria'),
--                                             ('NU', 'NIU', 'Niue'),
--                                             ('NF', 'NFK', 'Norfolk Island'),
--                                             ('MP', 'MNP', 'Northern Mariana Islands'),
--                                             ('NO', 'NOR', 'Norway'),
--                                             ('OM', 'OMN', 'Oman'),
--                                             ('PK', 'PAK', 'Pakistan'),
--                                             ('PW', 'PLW', 'Palau'),
--                                             ('PS', 'PSE', 'Palestinian Territory Occupied'),
--                                             ('PA', 'PAN', 'Panama'),
--                                             ('PG', 'PNG', 'Papua New Guinea'),
--                                             ('PY', 'PRY', 'Paraguay'),
--                                             ('PE', 'PER', 'Peru'),
--                                             ('PH', 'PHL', 'Philippines'),
--                                             ('PN', 'PCN', 'Pitcairn Islands'),
--                                             ('PL', 'POL', 'Poland'),
--                                             ('PT', 'PRT', 'Portugal'),
--                                             ('PR', 'PRI', 'Puerto Rico'),
--                                             ('QA', 'QAT', 'Qatar'),
--                                             ('RE', 'REU', 'Reunion'),
--                                             ('RO', 'ROU', 'Romania'),
--                                             ('RU', 'RUS', 'Russia'),
--                                             ('RW', 'RWA', 'Rwanda'),
--                                             ('BL', 'BLM', 'Saint Barthelemy'),
--                                             ('SH', 'SHN', 'Saint Helena'),
--                                             ('KN', 'KNA', 'Saint Kitts and Nevis'),
--                                             ('LC', 'LCA', 'Saint Lucia'),
--                                             ('MF', 'MAF', 'Saint Martin'),
--                                             ('PM', 'SPM', 'Saint Pierre and Miquelon'),
--                                             ('VC', 'VCT', 'Saint Vincent and the Grenadines'),
--                                             ('WS', 'WSM', 'Samoa'),
--                                             ('SM', 'SMR', 'San Marino'),
--                                             ('ST', 'STP', 'Sao Tome and Principe'),
--                                             ('SA', 'SAU', 'Saudi Arabia'),
--                                             ('SN', 'SEN', 'Senegal'),
--                                             ('RS', 'SRB', 'Serbia'),
--                                             ('SC', 'SYC', 'Seychelles'),
--                                             ('SL', 'SLE', 'Sierra Leone'),
--                                             ('SG', 'SGP', 'Singapore'),
--                                             ('SK', 'SVK', 'Slovakia'),
--                                             ('SI', 'SVN', 'Slovenia'),
--                                             ('SB', 'SLB', 'Solomon Islands'),
--                                             ('SO', 'SOM', 'Somalia'),
--                                             ('ZA', 'ZAF', 'South Africa'),
--                                             ('GS', 'SGS', 'South Georgia and the South Sandwich Islands'),
--                                             ('SS', 'SSD', 'South Sudan'),
--                                             ('ES', 'ESP', 'Spain'),
--                                             ('LK', 'LKA', 'Sri Lanka'),
--                                             ('SD', 'SDN', 'Sudan'),
--                                             ('SR', 'SUR', 'Suriname'),
--                                             ('SJ', 'SJM', 'Svalbard and Jan Mayen'),
--                                             ('SZ', 'SWZ', 'Swaziland'),
--                                             ('SE', 'SWE', 'Sweden'),
--                                             ('CH', 'CHE', 'Switzerland'),
--                                             ('SY', 'SYR', 'Syria'),
--                                             ('TW', 'TWN', 'Taiwan'),
--                                             ('TJ', 'TJK', 'Tajikistan'),
--                                             ('TZ', 'TZA', 'Tanzania'),
--                                             ('TH', 'THA', 'Thailand'),
--                                             ('TG', 'TGO', 'Togo'),
--                                             ('TK', 'TKL', 'Tokelau'),
--                                             ('TO', 'TON', 'Tonga'),
--                                             ('TT', 'TTO', 'Trinidad and Tobago'),
--                                             ('TN', 'TUN', 'Tunisia'),
--                                             ('TR', 'TUR', 'Turkey'),
--                                             ('TM', 'TKM', 'Turkmenistan'),
--                                             ('TC', 'TCA', 'Turks and Caicos Islands'),
--                                             ('TV', 'TUV', 'Tuvalu'),
--                                             ('UG', 'UGA', 'Uganda'),
--                                             ('UA', 'UKR', 'Ukraine'),
--                                             ('AE', 'ARE', 'United Arab Emirates'),
--                                             ('GB', 'GBR', 'United Kingdom'),
--                                             ('US', 'USA', 'United States'),
--                                             ('UM', 'UMI', 'United States Minor Outlying Islands'),
--                                             ('UY', 'URY', 'Uruguay'),
--                                             ('UZ', 'UZB', 'Uzbekistan'),
--                                             ('VU', 'VUT', 'Vanuatu'),
--                                             ('VA', 'VAT', 'Vatican City State'),
--                                             ('VE', 'VEN', 'Venezuela'),
--                                             ('VN', 'VNM', 'Vietnam'),
--                                             ('VG', 'VGB', 'Virgin Islands (British)'),
--                                             ('VI', 'VIR', 'Virgin Islands (US)'),
--                                             ('WF', 'WLF', 'Wallis and Futuna'),
--                                             ('EH', 'ESH', 'Western Sahara'),
--                                             ('YE', 'YEM', 'Yemen'),
--                                             ('ZM', 'ZMB', 'Zambia'),
--                                             ('ZW', 'ZWE', 'Zimbabwe');




-- INSERT INTO countriesTR (iso2, iso3, name) VALUES
--                                            ('AF', 'AFG', 'Afganistan'),
--                                            ('AX', 'ALA', 'Aland Adaları'),
--                                            ('AL', 'ALB', 'Arnavutluk'),
--                                            ('DZ', 'DZA', 'Cezayir'),
--                                            ('AS', 'ASM', 'Amerikan Samoası'),
--                                            ('AD', 'AND', 'Andorra'),
--                                            ('AO', 'AGO', 'Angola'),
--                                            ('AI', 'AIA', 'Anguilla'),
--                                            ('AQ', 'ATA', 'Antarktika'),
--                                            ('AG', 'ATG', 'Antigua ve Barbuda'),
--                                            ('AR', 'ARG', 'Arjantin'),
--                                            ('AM', 'ARM', 'Ermenistan'),
--                                            ('AW', 'ABW', 'Aruba'),
--                                            ('AU', 'AUS', 'Avustralya'),
--                                            ('AT', 'AUT', 'Avusturya'),
--                                            ('AZ', 'AZE', 'Azerbaycan'),
--                                            ('BS', 'BHS', 'Bahamalar'),
--                                            ('BH', 'BHR', 'Bahreyn'),
--                                            ('BD', 'BGD', 'Bangladeş'),
--                                            ('BB', 'BRB', 'Barbados'),
--                                            ('BY', 'BLR', 'Belarus'),
--                                            ('BE', 'BEL', 'Belçika'),
--                                            ('BZ', 'BLZ', 'Belize'),
--                                            ('BJ', 'BEN', 'Benin'),
--                                            ('BM', 'BMU', 'Bermuda'),
--                                            ('BT', 'BTN', 'Bhutan'),
--                                            ('BO', 'BOL', 'Bolivya'),
--                                            ('BA', 'BIH', 'Bosna-Hersek'),
--                                            ('BW', 'BWA', 'Botsvana'),
--                                            ('BV', 'BVT', 'Bouvet Adası'),
--                                            ('BR', 'BRA', 'Brezilya'),
--                                            ('IO', 'IOT', 'Britanya Hint Okyanusu Toprakları'),
--                                            ('BN', 'BRN', 'Brunei'),
--                                            ('BG', 'BGR', 'Bulgaristan'),
--                                            ('BF', 'BFA', 'Burkina Faso'),
--                                            ('BI', 'BDI', 'Burundi'),
--                                            ('KH', 'KHM', 'Kamboçya'),
--                                            ('CM', 'CMR', 'Kamerun'),
--                                            ('CA', 'CAN', 'Kanada'),
--                                            ('CV', 'CPV', 'Cape Verde'),
--                                            ('KY', 'CYM', 'Cayman Adaları'),
--                                            ('CF', 'CAF', 'Orta Afrika Cumhuriyeti'),
--                                            ('TD', 'TCD', 'Çad'),
--                                            ('CL', 'CHL', 'Şili'),
--                                            ('CN', 'CHN', 'Çin'),
--                                            ('CX', 'CXR', 'Christmas Adası'),
--                                            ('CC', 'CCK', 'Cocos Adaları'),
--                                            ('CO', 'COL', 'Kolombiya'),
--                                            ('KM', 'COM', 'Komorlar'),
--                                            ('CG', 'COG', 'Kongo'),
--                                            ('CD', 'COD', 'Demokratik Kongo Cumhuriyeti'),
--                                            ('CK', 'COK', 'Cook Adaları'),
--                                            ('CR', 'CRI', 'Kosta Rika'),
--                                            ('CI', 'CIV', 'Fildişi Sahili (Côte d''Ivoire)'),
--                                             ('HR', 'HRV', 'Hırvatistan'),
--                                             ('CU', 'CUB', 'Küba'),
--                                             ('CY', 'CYP', 'Kıbrıs'),
--                                             ('CZ', 'CZE', 'Çek Cumhuriyeti'),
--                                             ('DK', 'DNK', 'Danimarka'),
--                                             ('DJ', 'DJI', 'Cibuti'),
--                                             ('DM', 'DMA', 'Dominika'),
--                                             ('DO', 'DOM', 'Dominik Cumhuriyeti'),
--                                             ('ET', 'EST', 'Doğu Türkistan'),
--                                             ('TL', 'TLS', 'Doğu Timor'),
--                                             ('EC', 'ECU', 'Ekvador'),
--                                             ('EG', 'EGY', 'Mısır'),
--                                             ('SV', 'SLV', 'El Salvador'),
--                                             ('GQ', 'GNQ', 'Ekvator Ginesi'),
--                                             ('ER', 'ERI', 'Eritre'),
--                                             ('EE', 'EST', 'Estonya'),
--                                             ('ET', 'ETH', 'Etiyopya'),
--                                             ('FK', 'FLK', 'Falkland Adaları'),
--                                             ('FO', 'FRO', 'Faroe Adaları'),
--                                             ('FJ', 'FJI', 'Fiji Adaları'),
--                                             ('FI', 'FIN', 'Finlandiya'),
--                                             ('FR', 'FRA', 'Fransa'),
--                                             ('GF', 'GUF', 'Fransız Guyanası'),
--                                             ('PF', 'PYF', 'Fransız Polinezyası'),
--                                             ('TF', 'ATF', 'Fransız Güney Toprakları'),
--                                             ('GA', 'GAB', 'Gabon'),
--                                             ('GM', 'GMB', 'Gambiya'),
--                                             ('GE', 'GEO', 'Gürcistan'),
--                                             ('DE', 'DEU', 'Almanya'),
--                                             ('GH', 'GHA', 'Gana'),
--                                             ('GI', 'GIB', 'Cebelitarık'),
--                                             ('GR', 'GRC', 'Yunanistan'),
--                                             ('GL', 'GRL', 'Grönland'),
--                                             ('GD', 'GRD', 'Grenada'),
--                                             ('GP', 'GLP', 'Guadeloupe'),
--                                             ('GU', 'GUM', 'Guam'),
--                                             ('GT', 'GTM', 'Guatemala'),
--                                             ('GG', 'GGY', 'Guernsey ve Alderney'),
--                                             ('GN', 'GIN', 'Gine'),
--                                             ('GW', 'GNB', 'Gine-Bissau'),
--                                             ('GY', 'GUY', 'Guyana'),
--                                             ('HT', 'HTI', 'Haiti'),
--                                             ('HM', 'HMD', 'Heard Adası ve McDonald Adaları'),
--                                             ('HN', 'HND', 'Honduras'),
--                                             ('HK', 'HKG', 'Hong Kong SAR'),
--                                             ('HU', 'HUN', 'Macaristan'),
--                                             ('IS', 'ISL', 'İzlanda'),
--                                             ('IN', 'IND', 'Hindistan'),
--                                             ('ID', 'IDN', 'Endonezya'),
--                                             ('IR', 'IRN', 'İran'),
--                                             ('IQ', 'IRQ', 'Irak'),
--                                             ('IE', 'IRL', 'İrlanda'),
--                                             ('IM', 'IMN', 'Man Adası'),
--                                             ('IL', 'ISR', 'İsrail'),
--                                             ('IT', 'ITA', 'İtalya'),
--                                             ('JM', 'JAM', 'Jamaika'),
--                                             ('JP', 'JPN', 'Japonya'),
--                                             ('JE', 'JEY', 'Jersey'),
--                                             ('JO', 'JOR', 'Ürdün'),
--                                             ('KZ', 'KAZ', 'Kazakistan'),
--                                             ('KE', 'KEN', 'Kenya'),
--                                             ('KI', 'KIR', 'Kiribati'),
--                                             ('KP', 'PRK', 'Kuzey Kore'),
--                                             ('KR', 'KOR', 'Güney Kore'),
--                                             ('KW', 'KWT', 'Kuveyt'),
--                                             ('KG', 'KGZ', 'Kırgızistan'),
--                                             ('LA', 'LAO', 'Laos'),
--                                             ('LV', 'LVA', 'Letonya'),
--                                             ('LB', 'LBN', 'Lübnan'),
--                                             ('LS', 'LSO', 'Lesotho'),
--                                             ('LR', 'LBR', 'Liberya'),
--                                             ('LY', 'LBY', 'Libya'),
--                                             ('LI', 'LIE', 'Lihtenştayn'),
--                                             ('LT', 'LTU', 'Litvanya'),
--                                             ('LU', 'LUX', 'Lüksemburg'),
--                                             ('MO', 'MAC', 'Makao SAR'),
--                                             ('MK', 'MKD', 'Kuzey Makedonya'),
--                                             ('MG', 'MDG', 'Madagaskar'),
--                                             ('MW', 'MWI', 'Malavi'),
--                                             ('MY', 'MYS', 'Malezya'),
--                                             ('MV', 'MDV', 'Maldivler'),
--                                             ('ML', 'MLI', 'Mali'),
--                                             ('MT', 'MLT', 'Malta'),
--                                             ('MH', 'MHL', 'Marshall Adaları'),
--                                             ('MQ', 'MTQ', 'Martinik'),
--                                             ('MR', 'MRT', 'Moritanya'),
--                                             ('MU', 'MUS', 'Mauritius'),
--                                             ('YT', 'MYT', 'Mayotte'),
--                                             ('MX', 'MEX', 'Meksika'),
--                                             ('FM', 'FSM', 'Mikronezya'),
--                                             ('MD', 'MDA', 'Moldova'),
--                                             ('MC', 'MCO', 'Monako'),
--                                             ('MN', 'MNG', 'Moğolistan'),
--                                             ('ME', 'MNE', 'Karadağ'),
--                                             ('MS', 'MSR', 'Montserrat'),
--                                             ('MA', 'MAR', 'Fas'),
--                                             ('MZ', 'MOZ', 'Mozambik'),
--                                             ('MM', 'MMR', 'Myanmar'),
--                                             ('NA', 'NAM', 'Namibya'),
--                                             ('NR', 'NRU', 'Nauru'),
--                                             ('NP', 'NPL', 'Nepal'),
--                                             ('NL', 'NLD', 'Hollanda'),
--                                             ('AN', 'ANT', 'Hollanda Antilleri'),
--                                             ('NC', 'NCL', 'Yeni Kaledonya'),
--                                             ('NZ', 'NZL', 'Yeni Zelanda'),
--                                             ('NI', 'NIC', 'Nikaragua'),
--                                             ('NE', 'NER', 'Nijer'),
--                                             ('NG', 'NGA', 'Nijerya'),
--                                             ('NU', 'NIU', 'Niue'),
--                                             ('NF', 'NFK', 'Norfolk Adası'),
--                                             ('MP', 'MNP', 'Kuzey Mariana Adaları'),
--                                             ('NO', 'NOR', 'Norveç'),
--                                             ('OM', 'OMN', 'Umman'),
--                                             ('PK', 'PAK', 'Pakistan'),
--                                             ('PW', 'PLW', 'Palau'),
--                                             ('PS', 'PSE', 'Filistin Toprakları'),
--                                             ('PA', 'PAN', 'Panama'),
--                                             ('PG', 'PNG', 'Papua Yeni Gine'),
--                                             ('PY', 'PRY', 'Paraguay'),
--                                             ('PE', 'PER', 'Peru'),
--                                             ('PH', 'PHL', 'Filipinler'),
--                                             ('PN', 'PCN', 'Pitcairn Adaları'),
--                                             ('PL', 'POL', 'Polonya'),
--                                             ('PT', 'PRT', 'Portekiz'),
--                                             ('PR', 'PRI', 'Porto Riko'),
--                                             ('QA', 'QAT', 'Katar'),
--                                             ('RE', 'REU', 'Reunion'),
--                                             ('RO', 'ROU', 'Romanya'),
--                                             ('RU', 'RUS', 'Rusya'),
--                                             ('RW', 'RWA', 'Ruanda'),
--                                             ('BL', 'BLM', 'Saint Barthelemy'),
--                                             ('SH', 'SHN', 'Saint Helena'),
--                                             ('KN', 'KNA', 'Saint Kitts ve Nevis'),
--                                             ('LC', 'LCA', 'Saint Lucia'),
--                                             ('MF', 'MAF', 'Saint Martin'),
--                                             ('PM', 'SPM', 'Saint Pierre ve Miquelon'),
--                                             ('VC', 'VCT', 'Saint Vincent ve Grenadinler'),
--                                             ('WS', 'WSM', 'Samoa'),
--                                             ('SM', 'SMR', 'San Marino'),
--                                             ('ST', 'STP', 'Sao Tome ve Principe'),
--                                             ('SA', 'SAU', 'Suudi Arabistan'),
--                                             ('SN', 'SEN', 'Senegal'),
--                                             ('RS', 'SRB', 'Sırbistan'),
--                                             ('SC', 'SYC', 'Seyşeller'),
--                                             ('SL', 'SLE', 'Sierra Leone'),
--                                             ('SG', 'SGP', 'Singapur'),
--                                             ('SK', 'SVK', 'Slovakya'),
--                                             ('SI', 'SVN', 'Slovenya'),
--                                             ('SB', 'SLB', 'Solomon Adaları'),
--                                             ('SO', 'SOM', 'Somali'),
--                                             ('ZA', 'ZAF', 'Güney Afrika'),
--                                             ('GS', 'SGS', 'Gürcistan Güney ve Güney Sandwich Adaları'),
--                                             ('SS', 'SSD', 'Güney Sudan'),
--                                             ('ES', 'ESP', 'İspanya'),
--                                             ('LK', 'LKA', 'Sri Lanka'),
--                                             ('SD', 'SDN', 'Sudan'),
--                                             ('SR', 'SUR', 'Surinam'),
--                                             ('SJ', 'SJM', 'Svalbard ve Jan Mayen'),
--                                             ('SZ', 'SWZ', 'Svaziland'),
--                                             ('SE', 'SWE', 'İsveç'),
--                                             ('CH', 'CHE', 'İsviçre'),
--                                             ('SY', 'SYR', 'Suriye'),
--                                             ('TW', 'TWN', 'Tayvan'),
--                                             ('TJ', 'TJK', 'Tacikistan'),
--                                             ('TZ', 'TZA', 'Tanzanya'),
--                                             ('TH', 'THA', 'Tayland'),
--                                             ('TG', 'TGO', 'Togo'),
--                                             ('TK', 'TKL', 'Tokelau'),
--                                             ('TO', 'TON', 'Tonga'),
--                                             ('TT', 'TTO', 'Trinidad ve Tobago'),
--                                             ('TN', 'TUN', 'Tunus'),
--                                             ('TR', 'TUR', 'Türkiye'),
--                                             ('TM', 'TKM', 'Türkmenistan'),
--                                             ('TC', 'TCA', 'Turks ve Caicos Adaları'),
--                                             ('TV', 'TUV', 'Tuvalu'),
--                                             ('UG', 'UGA', 'Uganda'),
--                                             ('UA', 'UKR', 'Ukrayna'),
--                                             ('AE', 'ARE', 'Birleşik Arap Emirlikleri'),
--                                             ('GB', 'GBR', 'Birleşik Krallık'),
--                                             ('US', 'USA', 'Amerika Birleşik Devletleri'),
--                                             ('UM', 'UMI', 'Amerika Birleşik Devletleri Küçük Dış Adaları'),
--                                             ('UY', 'URY', 'Uruguay'),
--                                             ('UZ', 'UZB', 'Özbekistan'),
--                                             ('VU', 'VUT', 'Vanuatu'),
--                                             ('VA', 'VAT', 'Vatikan Şehir Devleti'),
--                                             ('VE', 'VEN', 'Venezuela'),
--                                             ('VN', 'VNM', 'Vietnam'),
--                                             ('VG', 'VGB', 'Virgin Adaları (Britanya)'),
--                                             ('VI', 'VIR', 'Virgin Adaları (ABD)'),
--                                             ('WF', 'WLF', 'Wallis ve Futuna'),
--                                             ('EH', 'ESH', 'Batı Sahara'),
--                                             ('YE', 'YEM', 'Yemen'),
--                                             ('ZM', 'ZMB', 'Zambiya'),
--                                             ('ZW', 'ZWE', 'Zimbabve');
