package com.etlas.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CountriesTr {
    AFG("AF", "AFG", "Afganistan"),
    ALA("AX", "ALA", "Aland Adaları"),
    ALB("AL", "ALB", "Arnavutluk"),
    DZA("DZ", "DZA", "Cezayir"),
    ASM("AS", "ASM", "Amerikan Samoası"),
    AND("AD", "AND", "Andorra"),
    AGO("AO", "AGO", "Angola"),
    AIA("AI", "AIA", "Anguilla"),
    ATA("AQ", "ATA", "Antarktika"),
    ATG("AG", "ATG", "Antigua ve Barbuda"),
    ARG("AR", "ARG", "Arjantin"),
    ARM("AM", "ARM", "Ermenistan"),
    ABW("AW", "ABW", "Aruba"),
    AUS("AU", "AUS", "Avustralya"),
    AUT("AT", "AUT", "Avusturya"),
    AZE("AZ", "AZE", "Azerbaycan"),
    BHS("BS", "BHS", "Bahamalar"),
    BHR("BH", "BHR", "Bahreyn"),
    BGD("BD", "BGD", "Bangladeş"),
    BRB("BB", "BRB", "Barbados"),
    BLR("BY", "BLR", "Belarus"),
    BEL("BE", "BEL", "Belçika"),
    BLZ("BZ", "BLZ", "Belize"),
    BEN("BJ", "BEN", "Benin"),
    BMU("BM", "BMU", "Bermuda"),
    BTN("BT", "BTN", "Bhutan"),
    BOL("BO", "BOL", "Bolivya"),
    BIH("BA", "BIH", "Bosna-Hersek"),
    BWA("BW", "BWA", "Botsvana"),
    BVT("BV", "BVT", "Bouvet Adası"),
    BRA("BR", "BRA", "Brezilya"),
    IOT("IO", "IOT", "Britanya Hint Okyanusu Toprakları"),
    BRN("BN", "BRN", "Brunei"),
    BGR("BG", "BGR", "Bulgaristan"),
    BFA("BF", "BFA", "Burkina Faso"),
    BDI("BI", "BDI", "Burundi"),
    KHM("KH", "KHM", "Kamboçya"),
    CMR("CM", "CMR", "Kamerun"),
    CAN("CA", "CAN", "Kanada"),
    CPV("CV", "CPV", "Cape Verde"),
    CYM("KY", "CYM", "Cayman Adaları"),
    CAF("CF", "CAF", "Orta Afrika Cumhuriyeti"),
    TCD("TD", "TCD", "Çad"),
    CHL("CL", "CHL", "Şili"),
    CHN("CN", "CHN", "Çin"),
    CXR("CX", "CXR", "Christmas Adası"),
    CCK("CC", "CCK", "Cocos Adaları"),
    COL("CO", "COL", "Kolombiya"),
    COM("KM", "COM", "Komorlar"),
    COG("CG", "COG", "Kongo"),
    COD("CD", "COD", "Demokratik Kongo Cumhuriyeti"),
    COK("CK", "COK", "Cook Adaları"),
    CRI("CR", "CRI", "Kosta Rika"),
    CIV("CI", "CIV", "Fildişi Sahili (Côte d'Ivoire)"),
    HRV("HR", "HRV", "Hırvatistan"),
    CUB("CU", "CUB", "Küba"),
    CYP("CY", "CYP", "Kıbrıs"),
    CZE("CZ", "CZE", "Çek Cumhuriyeti"),
    DNK("DK", "DNK", "Danimarka"),
    DJI("DJ", "DJI", "Cibuti"),
    DMA("DM", "DMA", "Dominika"),
    DOM("DO", "DOM", "Dominik Cumhuriyeti"),
    EAT("ET", "EAT", "Doğu Türkistan"),
    TLS("TL", "TLS", "Doğu Timor"),
    ECU("EC", "ECU", "Ekvador"),
    EGY("EG", "EGY", "Mısır"),
    SLV("SV", "SLV", "El Salvador"),
    GNQ("GQ", "GNQ", "Ekvator Ginesi"),
    ERI("ER", "ERI", "Eritre"),
    EST("EE", "EST", "Estonya"),
    ETH("ET", "ETH", "Etiyopya"),
    FLK("FK", "FLK", "Falkland Adaları"),
    FRO("FO", "FRO", "Faroe Adaları"),
    FJI("FJ", "FJI", "Fiji Adaları"),
    FIN("FI", "FIN", "Finlandiya"),
    FRA("FR", "FRA", "Fransa"),
    GUF("GF", "GUF", "Fransız Guyanası"),
    PYF("PF", "PYF", "Fransız Polinezyası"),
    ATF("TF", "ATF", "Fransız Güney Toprakları"),
    GAB("GA", "GAB", "Gabon"),
    GMB("GM", "GMB", "Gambiya"),
    GEO("GE", "GEO", "Gürcistan"),
    DEU("DE", "DEU", "Almanya"),
    GHA("GH", "GHA", "Gana"),
    GIB("GI", "GIB", "Cebelitarık"),
    GRC("GR", "GRC", "Yunanistan"),
    GRL("GL", "GRL", "Grönland"),
    GRD("GD", "GRD", "Grenada"),
    GLP("GP", "GLP", "Guadeloupe"),
    GUM("GU", "GUM", "Guam"),
    GTM("GT", "GTM", "Guatemala"),
    GGY("GG", "GGY", "Guernsey ve Alderney"),
    GIN("GN", "GIN", "Gine"),
    GNB("GW", "GNB", "Gine-Bissau"),
    GUY("GY", "GUY", "Guyana"),
    HTI("HT", "HTI", "Haiti"),
    HMD("HM", "HMD", "Heard Adası ve McDonald Adaları"),
    HND("HN", "HND", "Honduras"),
    HKG("HK", "HKG", "Hong Kong SAR"),
    HUN("HU", "HUN", "Macaristan"),
    ISL("IS", "ISL", "İzlanda"),
    IND("IN", "IND", "Hindistan"),
    IDN("ID", "IDN", "Endonezya"),
    IRN("IR", "IRN", "İran"),
    IRQ("IQ", "IRQ", "Irak"),
    IRL("IE", "IRL", "İrlanda"),
    IMN("IM", "IMN", "Man Adası"),
    ISR("IL", "ISR", "İsrail"),
    ITA("IT", "ITA", "İtalya"),
    JAM("JM", "JAM", "Jamaika"),
    JPN("JP", "JPN", "Japonya"),
    JEY("JE", "JEY", "Jersey"),
    JOR("JO", "JOR", "Ürdün"),
    KAZ("KZ", "KAZ", "Kazakistan"),
    KEN("KE", "KEN", "Kenya"),
    KIR("KI", "KIR", "Kiribati"),
    PRK("KP", "PRK", "Kuzey Kore"),
    KOR("KR", "KOR", "Güney Kore"),
    KWT("KW", "KWT", "Kuveyt"),
    KGZ("KG", "KGZ", "Kırgızistan"),
    LAO("LA", "LAO", "Laos"),
    LVA("LV", "LVA", "Letonya"),
    LBN("LB", "LBN", "Lübnan"),
    LSO("LS", "LSO", "Lesotho"),
    LBR("LR", "LBR", "Liberya"),
    LBY("LY", "LBY", "Libya"),
    LIE("LI", "LIE", "Lihtenştayn"),
    LTU("LT", "LTU", "Litvanya"),
    LUX("LU", "LUX", "Lüksemburg"),
    MAC("MO", "MAC", "Makao SAR"),
    MKD("MK", "MKD", "Kuzey Makedonya"),
    MDG("MG", "MDG", "Madagaskar"),
    MWI("MW", "MWI", "Malavi"),
    MYS("MY", "MYS", "Malezya"),
    MDV("MV", "MDV", "Maldivler"),
    MLI("ML", "MLI", "Mali"),
    MLT("MT", "MLT", "Malta"),
    MHL("MH", "MHL", "Marshall Adaları"),
    MTQ("MQ", "MTQ", "Martinik"),
    MRT("MR", "MRT", "Moritanya"),
    MUS("MU", "MUS", "Mauritius"),
    MYT("YT", "MYT", "Mayotte"),
    MEX("MX", "MEX", "Meksika"),
    FSM("FM", "FSM", "Mikronezya"),
    MDA("MD", "MDA", "Moldova"),
    MCO("MC", "MCO", "Monako"),
    MNG("MN", "MNG", "Moğolistan"),
    MNE("ME", "MNE", "Karadağ"),
    MSR("MS", "MSR", "Montserrat"),
    MAR("MA", "MAR", "Fas"),
    MOZ("MZ", "MOZ", "Mozambik"),
    MMR("MM", "MMR", "Myanmar"),
    NAM("NA", "NAM", "Namibya"),
    NRU("NR", "NRU", "Nauru"),
    NPL("NP", "NPL", "Nepal"),
    NLD("NL", "NLD", "Hollanda"),
    ANT("AN", "ANT", "Hollanda Antilleri"),
    NCL("NC", "NCL", "Yeni Kaledonya"),
    NZL("NZ", "NZL", "Yeni Zelanda"),
    NIC("NI", "NIC", "Nikaragua"),
    NER("NE", "NER", "Nijer"),
    NGA("NG", "NGA", "Nijerya"),
    NIU("NU", "NIU", "Niue"),
    NFK("NF", "NFK", "Norfolk Adası"),
    MNP("MP", "MNP", "Kuzey Mariana Adaları"),
    NOR("NO", "NOR", "Norveç"),
    OMN("OM", "OMN", "Umman"),
    PAK("PK", "PAK", "Pakistan"),
    PLW("PW", "PLW", "Palau"),
    PSE("PS", "PSE", "Filistin Toprakları"),
    PAN("PA", "PAN", "Panama"),
    PNG("PG", "PNG", "Papua Yeni Gine"),
    PRY("PY", "PRY", "Paraguay"),
    PER("PE", "PER", "Peru"),
    PHL("PH", "PHL", "Filipinler"),
    PCN("PN", "PCN", "Pitcairn Adaları"),
    POL("PL", "POL", "Polonya"),
    PRT("PT", "PRT", "Portekiz"),
    PRI("PR", "PRI", "Porto Riko"),
    QAT("QA", "QAT", "Katar"),
    REU("RE", "REU", "Reunion"),
    ROU("RO", "ROU", "Romanya"),
    RUS("RU", "RUS", "Rusya"),
    RWA("RW", "RWA", "Ruanda"),
    BLM("BL", "BLM", "Saint Barthelemy"),
    SHN("SH", "SHN", "Saint Helena"),
    KNA("KN", "KNA", "Saint Kitts ve Nevis"),
    LCA("LC", "LCA", "Saint Lucia"),
    MAF("MF", "MAF", "Saint Martin"),
    SPM("PM", "SPM", "Saint Pierre ve Miquelon"),
    VCT("VC", "VCT", "Saint Vincent ve Grenadinler"),
    WSM("WS", "WSM", "Samoa"),
    SMR("SM", "SMR", "San Marino"),
    STP("ST", "STP", "Sao Tome ve Principe"),
    SAU("SA", "SAU", "Suudi Arabistan"),
    SEN("SN", "SEN", "Senegal"),
    SRB("RS", "SRB", "Sırbistan"),
    SYC("SC", "SYC", "Seyşeller"),
    SLE("SL", "SLE", "Sierra Leone"),
    SGP("SG", "SGP", "Singapur"),
    SVK("SK", "SVK", "Slovakya"),
    SVN("SI", "SVN", "Slovenya"),
    SLB("SB", "SLB", "Solomon Adaları"),
    SOM("SO", "SOM", "Somali"),
    ZAF("ZA", "ZAF", "Güney Afrika"),
    SGS("GS", "SGS", "Gürcistan Güney ve Güney Sandwich Adaları"),
    SSD("SS", "SSD", "Güney Sudan"),
    ESP("ES", "ESP", "İspanya"),
    LKA("LK", "LKA", "Sri Lanka"),
    SDN("SD", "SDN", "Sudan"),
    SUR("SR", "SUR", "Surinam"),
    SJM("SJ", "SJM", "Svalbard ve Jan Mayen"),
    SWZ("SZ", "SWZ", "Svaziland"),
    SWE("SE", "SWE", "İsveç"),
    CHE("CH", "CHE", "İsviçre"),
    SYR("SY", "SYR", "Suriye"),
    TWN("TW", "TWN", "Tayvan"),
    TJK("TJ", "TJK", "Tacikistan"),
    TZA("TZ", "TZA", "Tanzanya"),
    THA("TH", "THA", "Tayland"),
    TGO("TG", "TGO", "Togo"),
    TKL("TK", "TKL", "Tokelau"),
    TON("TO", "TON", "Tonga"),
    TTO("TT", "TTO", "Trinidad ve Tobago"),
    TUN("TN", "TUN", "Tunus"),
    TUR("TR", "TUR", "Türkiye"),
    TKM("TM", "TKM", "Türkmenistan"),
    TCA("TC", "TCA", "Turks ve Caicos Adaları"),
    TUV("TV", "TUV", "Tuvalu"),
    UGA("UG", "UGA", "Uganda"),
    UKR("UA", "UKR", "Ukrayna"),
    ARE("AE", "ARE", "Birleşik Arap Emirlikleri"),
    GBR("GB", "GBR", "Birleşik Krallık"),
    USA("US", "USA", "Amerika Birleşik Devletleri"),
    UMI("UM", "UMI", "Amerika Birleşik Devletleri Küçük Dış Adaları"),
    URY("UY", "URY", "Uruguay"),
    UZB("UZ", "UZB", "Özbekistan"),
    VUT("VU", "VUT", "Vanuatu"),
    VAT("VA", "VAT", "Vatikan Şehir Devleti"),
    VEN("VE", "VEN", "Venezuela"),
    VNM("VN", "VNM", "Vietnam"),
    VGB("VG", "VGB", "Virgin Adaları (Britanya)"),
    VIR("VI", "VIR", "Virgin Adaları (ABD)"),
    WLF("WF", "WLF", "Wallis ve Futuna"),
    ESH("EH", "ESH", "Batı Sahara"),
    YEM("YE", "YEM", "Yemen"),
    ZMB("ZM", "ZMB", "Zambiya"),
    ZWE("ZW", "ZWE", "Zimbabve");

    private final String alpha2Code;
    private final String alpha3Code;
    private final String name;
}
