package com.etlas.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CountriesEn {
    AFGHANISTAN("AF", "AFG", "Afghanistan"),
    ALAND_ISLANDS("AX", "ALA", "Aland Islands"),
    ALBANIA("AL", "ALB", "Albania"),
    ALGERIA("DZ", "DZA", "Algeria"),
    AMERICAN_SAMOA("AS", "ASM", "American Samoa"),
    ANDORRA("AD", "AND", "Andorra"),
    ANGOLA("AO", "AGO", "Angola"),
    ANGUILLA("AI", "AIA", "Anguilla"),
    ANTARCTICA("AQ", "ATA", "Antarctica"),
    ANTIGUA_AND_BARBUDA("AG", "ATG", "Antigua And Barbuda"),
    ARGENTINA("AR", "ARG", "Argentina"),
    ARMENIA("AM", "ARM", "Armenia"),
    ARUBA("AW", "ABW", "Aruba"),
    AUSTRALIA("AU", "AUS", "Australia"),
    AUSTRIA("AT", "AUT", "Austria"),
    AZERBAIJAN("AZ", "AZE", "Azerbaijan"),
    BAHAMAS("BS", "BHS", "The Bahamas"),
    BAHRAIN("BH", "BHR", "Bahrain"),
    BANGLADESH("BD", "BGD", "Bangladesh"),
    BARBADOS("BB", "BRB", "Barbados"),
    BELARUS("BY", "BLR", "Belarus"),
    BELGIUM("BE", "BEL", "Belgium"),
    BELIZE("BZ", "BLZ", "Belize"),
    BENIN("BJ", "BEN", "Benin"),
    BERMUDA("BM", "BMU", "Bermuda"),
    BHUTAN("BT", "BTN", "Bhutan"),
    BOLIVIA("BO", "BOL", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("BA", "BIH", "Bosnia and Herzegovina"),
    BOTSWANA("BW", "BWA", "Botswana"),
    BOUVET_ISLAND("BV", "BVT", "Bouvet Island"),
    BRAZIL("BR", "BRA", "Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("IO", "IOT", "British Indian Ocean Territory"),
    BRUNEI("BN", "BRN", "Brunei"),
    BULGARIA("BG", "BGR", "Bulgaria"),
    BURKINA_FASO("BF", "BFA", "Burkina Faso"),
    BURUNDI("BI", "BDI", "Burundi"),
    CAMBODIA("KH", "KHM", "Cambodia"),
    CAMEROON("CM", "CMR", "Cameroon"),
    CANADA("CA", "CAN", "Canada"),
    CAPE_VERDE("CV", "CPV", "Cape Verde"),
    CAYMAN_ISLANDS("KY", "CYM", "Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "CAF", "Central African Republic"),
    CHAD("TD", "TCD", "Chad"),
    CHILE("CL", "CHL", "Chile"),
    CHINA("CN", "CHN", "China"),
    CHRISTMAS_ISLAND("CX", "CXR", "Christmas Island"),
    COCOS_KEELING_ISLANDS("CC", "CCK", "Cocos (Keeling) Islands"),
    COLOMBIA("CO", "COL", "Colombia"),
    COMOROS("KM", "COM", "Comoros"),
    CONGO("CG", "COG", "Congo"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("CD", "COD", "Democratic Republic of the Congo"),
    COOK_ISLANDS("CK", "COK", "Cook Islands"),
    COSTA_RICA("CR", "CRI", "Costa Rica"),
    COTE_DIVOIRE_IVORY_COAST("CI", "CIV", "Cote D'Ivoire (Ivory Coast)"),
    CROATIA("HR", "HRV", "Croatia"),
    CUBA("CU", "CUB", "Cuba"),
    CYPRUS("CY", "CYP", "Cyprus"),
    CZECH_REPUBLIC("CZ", "CZE", "Czech Republic"),
    DENMARK("DK", "DNK", "Denmark"),
    DJIBOUTI("DJ", "DJI", "Djibouti"),
    DOMINICA("DM", "DMA", "Dominica"),
    DOMINICAN_REPUBLIC("DO", "DOM", "Dominican Republic"),
    EAST_TURKISTAN("ET","EAT","East Turkistan"),
    EAST_TIMOR("TL", "TLS", "East Timor"),
    ECUADOR("EC", "ECU", "Ecuador"),
    EGYPT("EG", "EGY", "Egypt"),
    EL_SALVADOR("SV", "SLV", "El Salvador"),
    EQUATORIAL_GUINEA("GQ", "GNQ", "Equatorial Guinea"),
    ERITREA("ER", "ERI", "Eritrea"),
    ESTONIA("EE", "EST", "Estonia"),
    ETHIOPIA("ET", "ETH", "Ethiopia"),
    FALKLAND_ISLANDS("FK", "FLK", "Falkland Islands"),
    FAROE_ISLANDS("FO", "FRO", "Faroe Islands"),
    FIJI_ISLANDS("FJ", "FJI", "Fiji Islands"),
    FINLAND("FI", "FIN", "Finland"),
    FRANCE("FR", "FRA", "France"),
    FRENCH_GUIANA("GF", "GUF", "French Guiana"),
    FRENCH_POLYNESIA("PF", "PYF", "French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("TF", "ATF", "French Southern Territories"),
    GABON("GA", "GAB", "Gabon"),
    GAMBIA_THE("GM", "GMB", "Gambia The"),
    GEORGIA("GE", "GEO", "Georgia"),
    GERMANY("DE", "DEU", "Germany"),
    GHANA("GH", "GHA", "Ghana"),
    GIBRALTAR("GI", "GIB", "Gibraltar"),
    GREECE("GR", "GRC", "Greece"),
    GREENLAND("GL", "GRL", "Greenland"),
    GRENADA("GD", "GRD", "Grenada"),
    GUADELOUPE("GP", "GLP", "Guadeloupe"),
    GUAM("GU", "GUM", "Guam"),
    GUATEMALA("GT", "GTM", "Guatemala"),
    GUERNSEY_AND_ALDERNEY("GG", "GGY", "Guernsey and Alderney"),
    GUINEA("GN", "GIN", "Guinea"),
    GUINEA_BISSAU("GW", "GNB", "Guinea-Bissau"),
    GUYANA("GY", "GUY", "Guyana"),
    HAITI("HT", "HTI", "Haiti"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS("HM", "HMD", "Heard Island and McDonald Islands"),
    HONDURAS("HN", "HND", "Honduras"),
    HONG_KONG_SAR("HK", "HKG", "Hong Kong SAR"),
    HUNGARY("HU", "HUN", "Hungary"),
    ICELAND("IS", "ISL", "Iceland"),
    INDIA("IN", "IND", "India"),
    INDONESIA("ID", "IDN", "Indonesia"),
    IRAN("IR", "IRN", "Iran"),
    IRAQ("IQ", "IRQ", "Iraq"),
    IRELAND("IE", "IRL", "Ireland"),
    ISLE_OF_MAN("IM", "IMN", "Isle of Man"),
    ISRAEL("IL", "ISR", "Israel"),
    ITALY("IT", "ITA", "Italy"),
    JAMAICA("JM", "JAM", "Jamaica"),
    JAPAN("JP", "JPN", "Japan"),
    JERSEY("JE", "JEY", "Jersey"),
    JORDAN("JO", "JOR", "Jordan"),
    KAZAKHSTAN("KZ", "KAZ", "Kazakhstan"),
    KENYA("KE", "KEN", "Kenya"),
    KIRIBATI("KI", "KIR", "Kiribati"),
    KOREA_NORTH("KP", "PRK", "Korea North"),
    KOREA_SOUTH("KR", "KOR", "Korea South"),
    KUWAIT("KW", "KWT", "Kuwait"),
    KYRGYZSTAN("KG", "KGZ", "Kyrgyzstan"),
    LAOS("LA", "LAO", "Laos"),
    LATVIA("LV", "LVA", "Latvia"),
    LEBANON("LB", "LBN", "Lebanon"),
    LESOTHO("LS", "LSO", "Lesotho"),
    LIBERIA("LR", "LBR", "Liberia"),
    LIBYA("LY", "LBY", "Libya"),
    LIECHTENSTEIN("LI", "LIE", "Liechtenstein"),
    LITHUANIA("LT", "LTU", "Lithuania"),
    LUXEMBOURG("LU", "LUX", "Luxembourg"),
    MACAO_SAR("MO", "MAC", "Macao SAR"),
    NORTH_MACEDONIA("MK", "MKD", "North Macedonia"),
    MADAGASCAR("MG", "MDG", "Madagascar"),
    MALAWI("MW", "MWI", "Malawi"),
    MALAYSIA("MY", "MYS", "Malaysia"),
    MALDIVES("MV", "MDV", "Maldives"),
    MALI("ML", "MLI", "Mali"),
    MALTA("MT", "MLT", "Malta"),
    MARSHALL_ISLANDS("MH", "MHL", "Marshall Islands"),
    MARTINIQUE("MQ", "MTQ", "Martinique"),
    MAURITANIA("MR", "MRT", "Mauritania"),
    MAURITIUS("MU", "MUS", "Mauritius"),
    MAYOTTE("YT", "MYT", "Mayotte"),
    MEXICO("MX", "MEX", "Mexico"),
    MICRONESIA("FM", "FSM", "Micronesia"),
    MOLDOVA("MD", "MDA", "Moldova"),
    MONACO("MC", "MCO", "Monaco"),
    MONGOLIA("MN", "MNG", "Mongolia"),
    MONTENEGRO("ME", "MNE", "Montenegro"),
    MONTSERRAT("MS", "MSR", "Montserrat"),
    MOROCCO("MA", "MAR", "Morocco"),
    MOZAMBIQUE("MZ", "MOZ", "Mozambique"),
    MYANMAR("MM", "MMR", "Myanmar"),
    NAMIBIA("NA", "NAM", "Namibia"),
    NAURU("NR", "NRU", "Nauru"),
    NEPAL("NP", "NPL", "Nepal"),
    NETHERLANDS("NL", "NLD", "Netherlands"),
    NETHERLANDS_ANTILLES("AN", "ANT", "Netherlands Antilles"),
    NEW_CALEDONIA("NC", "NCL", "New Caledonia"),
    NEW_ZEALAND("NZ", "NZL", "New Zealand"),
    NICARAGUA("NI", "NIC", "Nicaragua"),
    NIGER("NE", "NER", "Niger"),
    NIGERIA("NG", "NGA", "Nigeria"),
    NIUE("NU", "NIU", "Niue"),
    NORFOLK_ISLAND("NF", "NFK", "Norfolk Island"),
    NORTHERN_MARIANA_ISLANDS("MP", "MNP", "Northern Mariana Islands"),
    NORWAY("NO", "NOR", "Norway"),
    OMAN("OM", "OMN", "Oman"),
    PAKISTAN("PK", "PAK", "Pakistan"),
    PALAU("PW", "PLW", "Palau"),
    PALESTINIAN_TERRITORY_OCCUPIED("PS", "PSE", "Palestinian Territory Occupied"),
    PANAMA("PA", "PAN", "Panama"),
    PAPUA_NEW_GUINEA("PG", "PNG", "Papua New Guinea"),
    PARAGUAY("PY", "PRY", "Paraguay"),
    PERU("PE", "PER", "Peru"),
    PHILIPPINES("PH", "PHL", "Philippines"),
    PITCAIRN_ISLANDS("PN", "PCN", "Pitcairn Islands"),
    POLAND("PL", "POL", "Poland"),
    PORTUGAL("PT", "PRT", "Portugal"),
    PUERTO_RICO("PR", "PRI", "Puerto Rico"),
    QATAR("QA", "QAT", "Qatar"),
    REUNION("RE", "REU", "Reunion"),
    ROMANIA("RO", "ROU", "Romania"),
    RUSSIA("RU", "RUS", "Russia"),
    RWANDA("RW", "RWA", "Rwanda"),
    SAINT_BARTHELEMY("BL", "BLM", "Saint Barthelemy"),
    SAINT_HELENA("SH", "SHN", "Saint Helena"),
    SAINT_KITTS_AND_NEVIS("KN", "KNA", "Saint Kitts and Nevis"),
    SAINT_LUCIA("LC", "LCA", "Saint Lucia"),
    SAINT_MARTIN("MF", "MAF", "Saint Martin"),
    SAINT_PIERRE_AND_MIQUELON("PM", "SPM", "Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "VCT", "Saint Vincent and the Grenadines"),
    SAMOA("WS", "WSM", "Samoa"),
    SAN_MARINO("SM", "SMR", "San Marino"),
    SAO_TOME_AND_PRINCIPE("ST", "STP", "Sao Tome and Principe"),
    SAUDI_ARABIA("SA", "SAU", "Saudi Arabia"),
    SENEGAL("SN", "SEN", "Senegal"),
    SERBIA("RS", "SRB", "Serbia"),
    SEYCHELLES("SC", "SYC", "Seychelles"),
    SIERRA_LEONE("SL", "SLE", "Sierra Leone"),
    SINGAPORE("SG", "SGP", "Singapore"),
    SLOVAKIA("SK", "SVK", "Slovakia"),
    SLOVENIA("SI", "SVN", "Slovenia"),
    SOLOMON_ISLANDS("SB", "SLB", "Solomon Islands"),
    SOMALIA("SO", "SOM", "Somalia"),
    SOUTH_AFRICA("ZA", "ZAF", "South Africa"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("GS", "SGS", "South Georgia and the South Sandwich Islands"),
    SOUTH_SUDAN("SS", "SSD", "South Sudan"),
    SPAIN("ES", "ESP", "Spain"),
    SRI_LANKA("LK", "LKA", "Sri Lanka"),
    SUDAN("SD", "SDN", "Sudan"),
    SURINAME("SR", "SUR", "Suriname"),
    SVALBARD_AND_JAN_MAYEN("SJ", "SJM", "Svalbard and Jan Mayen"),
    SWAZILAND("SZ", "SWZ", "Swaziland"),
    SWEDEN("SE", "SWE", "Sweden"),
    SWITZERLAND("CH", "CHE", "Switzerland"),
    SYRIA("SY", "SYR", "Syria"),
    TAIWAN("TW", "TWN", "Taiwan"),
    TAJIKISTAN("TJ", "TJK", "Tajikistan"),
    TANZANIA("TZ", "TZA", "Tanzania"),
    THAILAND("TH", "THA", "Thailand"),
    TOGO("TG", "TGO", "Togo"),
    TOKELAU("TK", "TKL", "Tokelau"),
    TONGA("TO", "TON", "Tonga"),
    TRINIDAD_AND_TOBAGO("TT", "TTO", "Trinidad and Tobago"),
    TUNISIA("TN", "TUN", "Tunisia"),
    TURKEY("TR", "TUR", "Turkey"),
    TURKMENISTAN("TM", "TKM", "Turkmenistan"),
    TURKS_AND_CAICOS_ISLANDS("TC", "TCA", "Turks and Caicos Islands"),
    TUVALU("TV", "TUV", "Tuvalu"),
    UGANDA("UG", "UGA", "Uganda"),
    UKRAINE("UA", "UKR", "Ukraine"),
    UNITED_ARAB_EMIRATES("AE", "ARE", "United Arab Emirates"),
    UNITED_KINGDOM("GB", "GBR", "United Kingdom"),
    UNITED_STATES("US", "USA", "United States"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("UM", "UMI", "United States Minor Outlying Islands"),
    URUGUAY("UY", "URY", "Uruguay"),
    UZBEKISTAN("UZ", "UZB", "Uzbekistan"),
    VANUATU("VU", "VUT", "Vanuatu"),
    VATICAN_CITY_STATE("VA", "VAT", "Vatican City State"),
    VENEZUELA("VE", "VEN", "Venezuela"),
    VIETNAM("VN", "VNM", "Vietnam"),
    VIRGIN_ISLANDS_BRITISH("VG", "VGB", "Virgin Islands (British)"),
    VIRGIN_ISLANDS_US("VI", "VIR", "Virgin Islands (US)"),
    WALLIS_AND_FUTUNA("WF", "WLF", "Wallis and Futuna"),
    WESTERN_SAHARA("EH", "ESH", "Western Sahara"),
    YEMEN("YE", "YEM", "Yemen"),
    ZAMBIA("ZM", "ZMB", "Zambia"),
    ZIMBABWE("ZW", "ZWE", "Zimbabwe");

    private final String iso2;
    private final String iso3;
    private final String name;
}


